In [35]:
import torch
torch.__version__

'2.8.0+cu126'

# Create a random tensor with shape (7, 7)


In [36]:
t1 = torch.tensor([7, 7])
t1

tensor([7, 7])

# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [49]:
t1 = torch.rand(7, 7)
t2 = torch.rand(1, 7)
torch.matmul(t1, t2.T)

tensor([[1.7079],
        [2.3925],
        [1.8437],
        [0.8302],
        [1.4080],
        [1.7865],
        [1.4289]])

# Set the random seed to `0` and do 2 & 3 over again.

In [38]:
torch.manual_seed(0)
t1 = torch.rand(7, 7)
t2 = torch.rand(1, 7)
torch.matmul(t1, t2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

# Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [39]:
torch.cuda.manual_seed(1234)

# Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [40]:
torch.cuda.is_available()

True

In [41]:
torch.manual_seed(1234)

x = torch.rand(2, 3)
y = torch.rand(2, 3)

x = x.to('cuda')
y = y.to('cuda')

print("Device:", x.device.type)
print((x, y))


Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0'), tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0'))


# Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [42]:
torch.manual_seed(1234)

t1 = torch.rand(2, 3, device='cuda')
t2 = torch.rand(2, 3, device='cuda')
x = torch.matmul(t1, t2.T)
x

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

# Find the maximum and minimum values of the output of 7.

In [43]:
torch.max(x) , torch.min(x)

(tensor(0.7668, device='cuda:0'), tensor(0.2786, device='cuda:0'))

# Find the maximum and minimum index values of the output of 7.

In [44]:
print(f"Index where max value occurs: {x.argmax()}") # -> 0.7668
print(f"Index where min value occurs: {x.argmin()}") # -> 0.2786

Index where max value occurs: 1
Index where min value occurs: 0


# Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [45]:
torch.manual_seed(7)

x = torch.rand(1, 1, 1, 10)

y = torch.squeeze(x)

print("First tensor (x):", x)
print("Shape of x:", x.shape)
print("\nSecond tensor (y):", y)
print("Shape of y:", y.shape)


First tensor (x): tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape of x: torch.Size([1, 1, 1, 10])

Second tensor (y): tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape of y: torch.Size([10])
